version: '1.0'

stages:
- preparation
- test
- build
- push
- run

steps:

  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: ${{GIT_CONTEXT}}

  install_dependencies:
    title: 'Installing testing dependencies'
    stage: preparation
    image: node:12.13.0
    commands:
    - yarn install --frozen-lockfile

  lint:
    title: 'lint code'
    stage: preparation
    image: node:12.13.0
    commands:
    - yarn lint


  build_step:
    title: "Building production image"
    stage: build
    type: build
    dockerfile: Dockerfile
    image_name: ${{IMAGE_NAME}}
    disable_push: true
    metadata:
      set:
      - CF_QUALITY: true

  build_rollback_action: 
    title: "Building rollback action image"
    stage: build
    type: build
    dockerfile: actions/rollback/Dockerfile
    image_name: ${{IMAGE_NAME}}-rollback
    disable_push: true
    metadata:
      set:
      - CF_QUALITY: true

  run_arm_build:
    type: codefresh-run
    stage: build
    arguments:
      PIPELINE_ID: ${{ARM_PIPELINE_ID}}
      DETACH: false
      VARIABLE:
        - CF_REPO_OWNER=${{CF_REPO_OWNER}}
        - CF_REPO_NAME=${{CF_REPO_NAME}}
        - CF_REVISION=${{CF_REVISION}}
        - CF_BRANCH=${{CF_BRANCH}}
        - CF_BRANCH_TAG_NORMALIZED=${{CF_BRANCH_TAG_NORMALIZED}}
        - GIT_CONTEXT=${{GIT_CONTEXT}}
        - IMAGE_NAME=${{IMAGE_NAME}}
        - IMAGE_NAME_ROLLBACK=${{IMAGE_NAME_ROLLBACK}}
        - ARM_TAG_POSTFIX="${{ARM_TAG_POSTFIX}}"

  push_rollback_action:
      title: 'Pushing rollback image to docker registries'
      stage: push
      type: push
      image_name: ${{IMAGE_NAME_ROLLBACK}}
      candidate: ${{build_rollback_action}}
      tags:
      - ${{CF_BRANCH_TAG_NORMALIZED}}
      - ${{CF_REVISION}}
      - latest
      when:
       branch:
        only:
         - master
      scale:
        push_quay_rollback_image:
          registry: "${{REGISTRY_INTEGRATION_QUAY}}"
        push_dockerhub_rollback_image:
          registry: "${{REGISTRY_INTEGRATION_DOCKERHUB}}"
        push_gcr_enterprise_rollback_image:
          registry: "${{REGISTRY_INTEGRATION_ENTERPRISE}}"

  push:
    title: 'Pushing image to docker registries'
    stage: push
    type: push
    image_name: ${{IMAGE_NAME}}
    candidate: ${{build_step}}
    tags:
    - ${{CF_BRANCH_TAG_NORMALIZED}}
    - ${{CF_REVISION}}
    - latest
    - stable
    when:
     branch:
      only:
       - master
    scale:
      push_quay:
        registry: "${{REGISTRY_INTEGRATION_QUAY}}"
      push_dockerhub:
        registry: "${{REGISTRY_INTEGRATION_DOCKERHUB}}"
      push_gcr_enterprise:
        registry: "${{REGISTRY_INTEGRATION_ENTERPRISE}}"

  create_manifest_list_rollback_image:
    stage: push
    type: "codefresh-inc/multiarch-manifester"
    when:
     branch:
      only:
       - master
    arguments:
      image_name: ${{IMAGE_NAME_ROLLBACK}}
      tags:
        - ${{CF_BRANCH_TAG_NORMALIZED}}
        - ${{CF_REVISION}}
        - latest
      arch_tag_postfixes: 
        arm64: "${{ARM_TAG_POSTFIX}}"
      registries:
        - name: 'quay.io'
          username: '${{QUAY_USERNAME}}'
          password: '${{QUAY_PASSWORD}}'
        - name: 'docker.io'
          username: '${{DOCKERHUB_USERNAME}}'
          password: '${{DOCKERHUB_PASSWORD}}'
        - name: 'gcr.io'
          path_prefix: codefresh-enterprise
          username: '${{GCR_USERNAME}}'
          password: '${{GCR_PASSWORD}}'

  create_manifest_list:
    stage: push
    type: "codefresh-inc/multiarch-manifester"
    when:
     branch:
      only:
       - master
    arguments:
      image_name: ${{IMAGE_NAME}}
      tags:
        - ${{CF_BRANCH_TAG_NORMALIZED}}
        - ${{CF_REVISION}}
        - latest
        - stable
      arch_tag_postfixes: 
        arm64: "${{ARM_TAG_POSTFIX}}"
      registries:
        - name: 'quay.io'
          username: '${{QUAY_USERNAME}}'
          password: '${{QUAY_PASSWORD}}'
        - name: 'docker.io'
          username: '${{DOCKERHUB_USERNAME}}'
          password: '${{DOCKERHUB_PASSWORD}}'
        - name: 'gcr.io'
          path_prefix: codefresh-enterprise
          username: '${{GCR_USERNAME}}'
          password: '${{GCR_PASSWORD}}'